### ISSUE TITLE
A few bugs 

### ISSUE THREAD

**Issue by dbd5** [lajax/yii2-asset-minifier#1]
Hi,

I did see a few bugs around path after configuration, do you have time to look at them?

PHP Warning – yii\base\ErrorException

file_get_contents(/var/www/advanced/frontend/web/vendor/revslider/js/jquery.themepunch.tools.min.js): failed to open stream: No such file or directory

The path /vendor/revslider/js/jquery.themepunch.tools.min.js is actually inside /var/www/advanced/frontend/web/assets

The declaration is the asset bundle is;  
public $baseUrl = '@web/assets';

**Comment by aidonsnous** [comment]
do you have any solution? I would like to use this extension too!!

**Comment by lajax** [comment]
Thanks for letting me know, I will fix this in a couple of days.

**Comment by dbd5** [comment]
Ok thanks

**Comment by aidonsnous** [comment]
Thanks !!! I am waiting.

**Comment by dbd5** [comment]
HI @lajax ,

Any progress on this?

**Comment by lajax** [comment]
Hi!

I'm quite busy these days, but 'll try to spend some time with it this weekend.

**Comment by dbd5** [comment]
Ok bro. And if there's anyway I can help - just ask

**Comment by dbd5** [comment]
Hi @lajax ,

I have updated code as necessary but this still throws exactly the same error!
composer didn't seem to pick up [515449d ](https://github.com/lajax/yii2-asset-minifier/commit/515449d41f68cfdc81be97bf61570e0d89f38057) so I had to remove it from composer.json and update - and then add it back and update again. 

I seems that the PATH passed to PhpJsMinifier.php by Minifier.php is wrong

The error thrown is;

file_get_contents(/var/www/advanced/frontend/web/vendor/revslider/js/jquery.themepunch.tools.min.js): failed to open stream: No such file or directory

The file you are looking for is actually in;
/var/www/advanced/frontend/web/**assets**/vendor/revslider/js/jquery.themepunch.tools.min.js

Here's the relevant Asset bundle

<?php
namespace frontend\assets;

use yii\web\AssetBundle;
class RevoAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web/assets';
    public $jsOptions = [
        'position' => \yii\web\View::POS_END,
    ];

```
public $css = [
    ["css/extralayers.css", "media"=>"screen",],
    ["vendor/revslider/css/settings.css", "media"=>"screen",],
];

public $js = [
    "vendor/revslider/js/jquery.themepunch.tools.min.js",
    "vendor/revslider/js/jquery.themepunch.revolution.min.js",
];

public $images = [
];

public $depends = [
    'frontend\assets\FrontendAsset',
];
```

}

Is there anything I can do to assist you troubleshoot this bug?
