### ISSUE TITLE
No Support for specifying Asset options using arrays in Asset bundles

### ISSUE THREAD

**Issue by dbd5** [lajax/yii2-asset-minifier#3]
Hello,

It appears that the extension throws an error when it encounters asset bundles where JS and CSS options are specified with arrays as follows (This has been supported by Yii since 2.0.7);

public $css = [
    'default_options.css',
    **['tv.css', 'media' => 'tv'],
    ['screen_and_print.css', 'media' => 'screen, print']**
];

public $js = [
    'normal.js',
    **['defered.js', 'defer' => true],**
];

The particular error message is;

**PHP Warning – yii\base\ErrorException; strncmp() expects parameter 1 to be string, array given**

Portion of Stack Trace
1. in /var/www/advanced/vendor/yiisoft/yii2/helpers/BaseUrl.php at line 350
   
   public static function isRelative($url)
   {
       return strncmp($url, '//', 2) && strpos($url, '://') === false;
   }
2. in /var/www/advanced/vendor/lajax/yii2-asset-minifier/src/Minifier.php at line 128 – yii\helpers\BaseUrl::isRelative()
   
   protected function minify($bundle, $filename)
   {
       if (Url::isRelative($filename)) {
           if ($this->workPath === self::WORKPATH_SOURCE) {
               $sourcePath = $bundle->sourcePath ? $bundle->sourcePath : Yii::getAlias('@webroot');
           } else {
               $sourcePath = $bundle->basePath;
           }
3. in /var/www/advanced/vendor/lajax/yii2-asset-minifier/src/Minifier.php at line 114 – lajax\assetminifier\Minifier::minify()

...

**Comment by moltam** [comment]
I'll look into this.
