### ISSUE TITLE
RuntimeException - Unclosed string at position: 2812

### ISSUE THREAD

**Issue by dbd5** [lajax/yii2-asset-minifier#4]
Hello,

This is a new error thrown after I commented out the Arrays used in the Asset bundles in #3 just to let the  extension carry on. 
1. in /var/www/advanced/vendor/tedivm/jshrink/src/JShrink/Minifier.php at line 476
2. in /var/www/advanced/vendor/tedivm/jshrink/src/JShrink/Minifier.php at line 231 – JShrink\Minifier::saveString()
   225226227228229230231232233234235236237                            if ($this->a === '/' && ($this->b === '\'' || $this->b === '"')) {
                               $this->saveRegex();
                               continue;
                           }
   
   ```
                       echo $this->a;
                       $this->saveString();
                       break;
               }
       }
   
       // do reg check of doom
       $this->b = $this->getReal();
   ```
3. in /var/www/advanced/vendor/tedivm/jshrink/src/JShrink/Minifier.php at line 144 – JShrink\Minifier::loop()

**Comment by moltam** [comment]
Hi,

I think this exception is caused by an invalid javascript code.

For example this produces the same exception (the code has a syntax error):

``` js
var bad = 'Hello 
world';
```

This works:

``` js
var bad = "Hello \
world";
```

More on this: http://stackoverflow.com/questions/805107/creating-multiline-strings-in-javascript

**Comment by dbd5** [comment]
Yea - I will look through the code again, thanks for all the support man!

**Comment by dbd5** [comment]
Hi @moltam ,

It it appears the javascript minifier didn't like this regex 
re = /[!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~]/;

So I replaced it with this and the error went away 
re = new RegExp("[!\"#$%&'()*+,\-./:;<=>?@[\]^_`{\|}~]");

**Comment by moltam** [comment]
Btw. the extension uses an external package for minifying: https://github.com/tedious/JShrink

You can report issues like this there.
